# Generated by Django 4.2.20 on 2025-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_orders_app', '0002_alter_order_items_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='cafe_orders_app.dish', verbose_name='Блюда'),
        ),
    ]
